**Numpy**

In [1]:
import numpy as np

In [2]:
myarr=np.array([6,27,4], np.int8)

In [3]:
myarr

array([ 6, 27,  4], dtype=int8)

In [4]:
myarr=np.array([[6,27,4]], np.int8)

In [5]:
myarr[0,1]

27

In [6]:
myarr.shape

(1, 3)

In [7]:
myarr.dtype

dtype('int8')

In [8]:
myarr[0,1]=45

In [9]:
myarr

array([[ 6, 45,  4]], dtype=int8)

**Conversion from other Python structures**

In [10]:
listarray=np.array([[1,2,3],[5,3,8],[0,3,1]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 3, 8],
       [0, 3, 1]])

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
listarray.dtype

dtype('int32')

**Intrinsic NumPy array creation functions**

In [16]:
zeros=np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.shape

(2, 5)

In [19]:
zeros.dtype

dtype('float64')

In [21]:
rng=np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(1,5,12)

In [24]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
emp=np.empty((4,6))

In [27]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        6.23039354e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 9.34598925e-307,
        1.42418715e-306, 1.95819401e-306, 1.37961370e-306],
       [6.23054633e-307, 9.34598926e-307, 6.89804132e-307,
        9.34598926e-307, 8.01091099e-307, 1.24610927e-306],
       [2.22522597e-306, 8.90109671e-307, 1.69119330e-306,
        9.34611148e-307, 2.22522596e-306, 2.56765117e-312]])

In [28]:
emp_like=np.empty_like(lspace)

In [30]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [31]:
ide=np.identity(45)

In [32]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
ide.shape

(45, 45)

In [34]:
arr=np.arange(99)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [39]:
ar=np.array(x)

In [40]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [41]:
ar.sum(axis=0)

array([12,  8,  9])

In [42]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.nbytes

36

In [48]:
one=np.array([1,3,4,634,2])

In [49]:
one.argmax()

3

In [51]:
one.argmin()

0

In [53]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar.argmin()

8

In [56]:
ar.argmax()

6

In [57]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [58]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [59]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [61]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [64]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [65]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [66]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [67]:
ar.sum()

29

In [68]:
ar.max()

7

In [69]:
ar.min()

0

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [73]:
type(np.where(ar>5))

tuple

In [74]:
np.count_nonzero(ar)

8

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [76]:
ar[1,2]=0

In [77]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [78]:
import sys

In [80]:
py_ar=[0,4,55,2]

In [81]:
np_ar=np.array(py_ar)

In [84]:
sys.getsizeof(1)*len(py_ar)

112

In [85]:
np_ar.itemsize*np_ar.size

16

In [86]:
np_ar.tolist()

[0, 4, 55, 2]